### ISSUE TITLE
Repayment status variables that are either string or numeric

### ISSUE THREAD

**Issue by kwanwkim** [btskinner/rscorecard#17]
When I make an API call for program-level columns on repayment status (e.g., % of borrowers in default),
```
sc_2018 <- sc_init() %>% 
  sc_filter(credlev==5) %>% 
  sc_select(unitid, opeid6, instnm, control, main, cipcode, cipdesc, credlev, creddesc, bbrr2_fed_comp_n,bbrr2_fed_comp_dflt,bbrr2_fed_comp_dlnq,bbrr2_fed_comp_fbr,bbrr2_fed_comp_dfr,bbrr2_fed_comp_noprog,bbrr2_fed_comp_makeprog,bbrr2_fed_comp_paidinfull,bbrr2_fed_comp_discharge) %>%
  sc_year(2018) %>% 
  sc_get()
```
It returns the following error:
```
Error in `list_unchop()`:
! Can't combine `x[[22]]$repayment.2_yr_bb_fed_comp.default` <character> and `x[[48]]$repayment.2_yr_bb_fed_comp.default` <double>.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by btskinner** [comment]
Just now seeing this. Is it still an issue? Sometimes the underlying data changes unexpectedly (and then changes back).

**Comment by kwanwkim** [comment]
It still is. I assume it's because program-level variables in debt are now offered either in actual values or value ranges (e.g., 0.3 - 0.4).

**Comment by btskinner** [comment]
Okay. If that's the case, I'll need a little bit to adjust the code to account for the new data type. If you are able, I'm glad to look at a pull request.

**Comment by kwanwkim** [comment]
Thank you!

**Comment by btskinner** [comment]
Okay I think I've fixed this. Download the newest release 0.28.0 from GitHub and try it out if you would:

```r
devtools::install_github("btskinner/rscorecard")
```

**Comment by kwanwkim** [comment]
Hi Benjamin,

Thank you very much for the update. Could you take a look at the following
error message, which newly appeared since the latest update? It occurs when
I pull the 2016 and 2017 data. The codes are attached at the end.


Error in `purrr::map2()`:
> ! Can't recycle `.x` (size 5) to match `.y` (size 71).
> Run `rlang::last_trace()` to see where the error occurred.
> > rlang::last_trace()
> <error/vctrs_error_incompatible_size>
> Error in `purrr::map2()`:
> ! Can't recycle `.x` (size 5) to match `.y` (size 71).
> ---
> Backtrace:
>     ▆
>  1. ├─... %>% sc_get()
>  2. └─rscorecard::sc_get(.)
>  3.   ├─base::suppressWarnings(...)
>  4.   │ └─base::withCallingHandlers(...)
>  5.   ├─tibble::as_tibble(...)
>  6.   └─purrr::map2(...)
> Run rlang::last_trace(drop = FALSE) to see 6 hidden frames.


And here's my code that returns the error.

> sc_2016 <- sc_init() %>%
>   sc_filter(credlev==5) %>%
>   sc_select(unitid, opeid6, instnm, control, main, cipcode, cipdesc,
> credlev, creddesc, ipedscount1, ipedscount2, bbrr1_fed_comp_dflt) %>%
>   sc_year(2016) %>%
>   sc_get()
>

**Comment by btskinner** [comment]
Try version 0.28.1 (the latest)

**Comment by kwanwkim** [comment]
It works perfectly. Thank you.

**Comment by btskinner** [comment]
Closing
