### ISSUE TITLE
Data Dictionary as Dataframe

### ISSUE THREAD

**Issue by aiccu** [btskinner/rscorecard#9]
Command for pull and storage of a simplified data dictionary in the form of a dataframe.

**Comment by btskinner** [comment]
Is the idea that only those variables in the search are returned in the data frame?

**Comment by aiccu** [comment]
I actually had a more general data frame in mind to give the user an idea of what selected variables are available. Not sure what most folks' workflow is, but particularly with Scorecard data, I'm always trying to remember the source and available variables. Even something as basic as storing the most current data dictionary as an .rda file by dev-category (completion, repayment, etc.) would be greatly helpful.  (https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx)

Also attaching a screenshot of a similar r package that interfaces with IPEDS - by using the ipeds_help() command, it pulls year-level (all tables), table level (all variables in a table) and variable level (all values in variable) into a data frame for analysts to review.
![image](https://user-images.githubusercontent.com/56412165/69984482-1082c900-14ee-11ea-9298-0cd3e24a0bc1.png) (link to [GitHub](https://github.com/jbryer/ipeds))

**Comment by btskinner** [comment]
Check out the newest release (v0.14.0), which has more robust `sc_dict()` command now. Specifically if you set the argument `return_df = TRUE`, it will return a tibble with your dictionary search. If you set `print_off = TRUE`, you won't seen anything printed to the console, which might be nice in some cases.

**Example**

```{r}
> dict_df <- sc_dict('state', print_off = TRUE, return_df = TRUE)
> dict_df
# A tibble: 61 x 8
   varname value label  description  source dev_friendly_na… dev_category notes 
   <chr>   <dbl> <chr>  <chr>        <chr>  <chr>            <chr>        <chr> 
 1 stabbr     NA NA     State postc… IPEDS  state            school       Shown…
 2 st_fips     1 Alaba… FIPS code f… IPEDS  state_fips       school       Shown…
 3 st_fips     2 Alaska FIPS code f… IPEDS  state_fips       school       Shown…
 4 st_fips     4 Arizo… FIPS code f… IPEDS  state_fips       school       Shown…
 5 st_fips     5 Arkan… FIPS code f… IPEDS  state_fips       school       Shown…
 6 st_fips     6 Calif… FIPS code f… IPEDS  state_fips       school       Shown…
 7 st_fips     8 Color… FIPS code f… IPEDS  state_fips       school       Shown…
 8 st_fips     9 Conne… FIPS code f… IPEDS  state_fips       school       Shown…
 9 st_fips    10 Delaw… FIPS code f… IPEDS  state_fips       school       Shown…
10 st_fips    11 Distr… FIPS code f… IPEDS  state_fips       school       Shown…
# … with 51 more rows
```
